### ISSUE TITLE
"/resources/conference-talks" Page Dead YouTube Link

### ISSUE THREAD

**Issue by johnjspiteri** [teambit/bit-dev#199]
On the "/resources/conference-talks" page, section "Scaling Team Delivery using Standardisation"... the YouTube video link is dead.

**Comment by debs-obrien** [comment]
hi @johnjspiteri thanks for creating the issue. However it seems to be working on my end. check it again and let me know if its still a problem for you. 

Thanks
<img width="1186" alt="CleanShot 2022-01-14 at 15 43 45@2x" src="https://user-images.githubusercontent.com/13063165/149534027-e0b99d90-9f9b-45b9-8c41-021ff30317df.png">

**Comment by johnjspiteri** [comment]
@debs-obrien, apologize for the delay... all good, must have been a brief network issue (I did check twice).

Thank you 👍
