### ISSUE TITLE
MDX not resolving anchor tags

### ISSUE THREAD

**Issue by jonatankBIT** [teambit/bit-dev#352]
MDX files are not properly resolving anchor tags.

Let's take for example one page at the Docs:
https://bit.dev/docs/frameworks/react/react-native-overview#compositions-issues

In this section, there is an anchor tag on `create a React Native Extension` That should take to the section `Create an extension`.

It has been done using the anchor tag:

```md
Let's [create a React Native extension](#create-an-extension) and add a `webpack-transformers.ts`
```

But when you click it, instead of taking to https://bit.dev/docs/frameworks/react/react-native-overview#create-an-extension
it redirects to https://bit.dev/docs/quick-start

**Comment by odedre** [comment]
looks like this was solved. closing.
@jonatankBIT please re open if this is still relevant
