### ISSUE TITLE
Routes are not prerendered

### ISSUE THREAD

**Issue by NitsanCohen770** [teambit/bit-dev#357]

**Comment by KutnerUri** [comment]
prerendering has been disabled - need to reactivate, at least for the basic common routes.

I updated pre-render webpack plugin in bit.dev, it should work now.
Let's start by prerendering the limited list of routes that we want:
- homepage
- thinking-in-components
- quick-start(s)
- aspects page

there's a problem getting the full list of links - the content components are to ESM, and the main app (which is CJS) cannot load them.
we can load esm from cjs using the dynamic `import()` method, but there are a couple of blockers:
- [ ] components are not marked as esm with `"type": "module"` in their package.json
  - [ ] I tried to do that, it just causes more errors from Webpack 😄 
- [ ] ts converts dynamic `import()`s to `require()`. --> need to use eval() to sneak around TS.
- [ ] v8-compiler-cache, an optimization we use, breaks with dynamic `import()`. Need to run build with `DISABLE_V8_COMPILE_CACHE=true`
